# -*- coding: utf-8 -*-
"""Trabalho Graficos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_-Ab2Cq8gnOwRBzxVLfcyutr299cXOR
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('/content/social-media-stocks-2012-2022-_1_.csv')
df = df.values.tolist()

Quantidade_de_Vendas, Menor_Valor,  Maior_Valor, Fechamento, Abertura, Empresa, Data = ([] for i in range(7))
ANOS_BRUTOS = ['2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022']

for i in range(len(df)):
  dataFrame = list(df[i])
  Data.append(dataFrame[0])
  Empresa.append(dataFrame[1])
  Abertura.append(dataFrame[2])
  Fechamento.append(dataFrame[3])
  Maior_Valor.append(dataFrame[4])
  Menor_Valor.append(dataFrame[5])
  Quantidade_de_Vendas.append(dataFrame[6])

datasParsed = { ano : list() for ano in ANOS_BRUTOS }

x = 0
while x < len(ANOS_BRUTOS):
    i = 0
    while i < len(Data):
        ano = list(Data[i])
        if (ano[2]==ANOS_BRUTOS[x][2] and ano[3]==ANOS_BRUTOS[x][3]) and (Data[i] not in datasParsed[ANOS_BRUTOS[x]]):
            datasParsed[ANOS_BRUTOS[x]].append(Data[i])
        i += 1
    x += 1

#Esse código separa as empresas
Facebook , Twitter, Pinterest, Snapchat, Etsy = ([] for i in range(5))
for i in range(len(Empresa)):
  if Empresa[i] == 'FB':
    Facebook.append(Empresa[i])
  elif Empresa[i] == 'TWTR':
    Twitter.append(Empresa[i])   
  elif Empresa[i] == 'PINS':
    Pinterest.append(Empresa[i])
  elif Empresa[i] == 'SNAP':
    Snapchat.append(Empresa[i])
  else:
    Etsy.append(Empresa[i])    

#Juntar dois anos (Exemplo de 2020 e 2021)
Data_2020_2021 = []

for i in datasParsed["2020"]:
  Data_2020_2021.append(i)

for i in datasParsed["2021"]:
  Data_2020_2021.append(i)  

#Gráfico de linha Quantidade e Data 2020 a 2021
fig = px.line(x = Data_2020_2021, y = Maior_Valor[6415:6415+505],title = 'Maior valor das ações nos anos de 2020 e 2021', color = Empresa[6415:6415+505])
fig.update_xaxes(title_text='Data')
fig.update_yaxes(title_text='Valor de venda')
fig.show()

#Calcula a média de abertura de cada ano do facebook

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,total = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'FB':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'FB':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'FB':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'FB':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'FB':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'FB':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'FB':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'FB':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'FB':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'FB':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'FB':
    total22.append(a[2])

total12 = sum(total12)/len(total12);total.append(total12) 
total13 = sum(total13)/len(total13);total.append(total13) 
total14 = sum(total14)/len(total14);total.append(total14) 
total15 = sum(total15)/len(total15);total.append(total15)
total16 = sum(total16)/len(total16);total.append(total16) 
total17 = sum(total17)/len(total17);total.append(total17)
total18 = sum(total18)/len(total18);total.append(total18) 
total19 = sum(total19)/len(total19);total.append(total19)
total20 = sum(total20)/len(total20);total.append(total20) 
total21 = sum(total21)/len(total21);total.append(total21)
total22 = sum(total22)/len(total22);total.append(total22) 

#Gráfico da media de abertura do facebook

fig4 = px.bar(x = ['2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'],y = total,title = 'Valor médio das aberturas das ações do facebook')
fig4.update_yaxes (title = 'Valor de abertura')
fig4.update_xaxes(title = 'Anos')
fig4.show()

#Gráfico de linha Quantidade e Data 2020 a 2021
fig = px.line(x = Data_2020_2021, y = Quantidade_de_Vendas[6415:6415+505],title = 'Quantidade de vendas das ações nos anos de 2020 e 2021', color = Empresa[6415:6415+505])
fig.update_xaxes(title_text='Data')
fig.update_yaxes(title_text='Quantidade de Vendas')
fig.show()

#Grafico de torta Quant de Vendas relação á empresas
cores = ['#3b5998','#00acee','#FFFC00','#E60023','#F56400']
fig2 = px.pie(values= Quantidade_de_Vendas, names= Empresa,hole = 0.5,title='Quantidade total de vendas nos anos de 2012 e 2022',color_discrete_sequence=cores)
fig2.show()

#Exemplo de Gráfico de analise de mercado que mostra quase todas as variáveis
fig3 = go.Figure(go.Candlestick(x = datasParsed['2015'],
                open=Abertura[0:252],
                high=Maior_Valor[0:252],
                low=Menor_Valor[0:252],
                close=Fechamento[0:252]))
fig3.update_layout(
    title='Análise de mercado no ano de 2015',
    yaxis_title='Valores máximos de venda',
    xaxis_title='Linha temporal')
fig3.show()

#Grafico menor valor de venda do facebook entre 2012 e 2021
fig = px.bar (x = Facebook , y = Quantidade_de_Vendas[8398-2488:8398], color = Facebook, title = 'Menor valor de venda do Facebook entre os anos de 2012 e 2021')
fig.show()

#Gráfico de teste

cores = ['#3b5998','#00acee','#F56400','#FFFC00','#E60023']
fig5 = px.area(x = Data, y = Quantidade_de_Vendas, color = Empresa,title = 'Gráfico de teste',facet_col = Empresa,color_discrete_sequence=cores)
fig5.show()

#Outro gráfico de teste

fig6 = px.line(x=Data, y = Fechamento,color = Empresa,
              title='Outro gráfico de teste')
fig6.update_xaxes(
    dtick="M1")
fig6.show()

#Calcula a média de abertura de cada ano de cada empresa

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,totalface = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'FB':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'FB':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'FB':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'FB':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'FB':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'FB':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'FB':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'FB':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'FB':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'FB':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'FB':
    total22.append(a[2])

total12 = sum(total12)/len(total12);totalface.append(total12) 
total13 = sum(total13)/len(total13);totalface.append(total13) 
total14 = sum(total14)/len(total14);totalface.append(total14) 
total15 = sum(total15)/len(total15);totalface.append(total15)
total16 = sum(total16)/len(total16);totalface.append(total16) 
total17 = sum(total17)/len(total17);totalface.append(total17)
total18 = sum(total18)/len(total18);totalface.append(total18) 
total19 = sum(total19)/len(total19);totalface.append(total19)
total20 = sum(total20)/len(total20);totalface.append(total20) 
total21 = sum(total21)/len(total21);totalface.append(total21)
total22 = sum(total22)/len(total22);totalface.append(total22) 

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,totaltwitter = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'TWTR':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'TWTR':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'TWTR':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'TWTR':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'TWTR':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'TWTR':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'TWTR':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'TWTR':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'TWTR':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'TWTR':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'TWTR':
    total22.append(a[2])

if len(total12)>=1:
  total12 = sum(total12)/len(total12);totaltwitter.append(total12) 
else:
  totaltwitter.append(0)  
if len(total13)>=1:
  total13 = sum(total13)/len(total13);totaltwitter.append(total13)  
else:
  totaltwitter.append(0)  
if len(total14)>=1:
  total14 = sum(total14)/len(total14);totaltwitter.append(total14) 
else:
  totaltwitter.append(0)  
if len(total15)>=1:
  total15 = sum(total15)/len(total15);totaltwitter.append(total15) 
else:
  totaltwitter.append(0)  
if len(total16)>=1:
  total16 = sum(total16)/len(total16);totaltwitter.append(total16) 
else:
  totaltwitter.append(0)  
if len(total17)>=1:
  total17 = sum(total17)/len(total17);totaltwitter.append(total17) 
else:
  totaltwitter.append(0)  
if len(total18)>=1:
  total18 = sum(total18)/len(total18);totaltwitter.append(total18) 
else:
  totaltwitter.append(0)  
if len(total19)>=1:
  total19 = sum(total19)/len(total19);totaltwitter.append(total19) 
else:
  totaltwitter.append(0)  
if len(total20)>=1:
  total20 = sum(total20)/len(total20);totaltwitter.append(total20) 
else:
  totaltwitter.append(0)  
if len(total21)>=1:
  total21 = sum(total21)/len(total21);totaltwitter.append(total21) 
else:
  totaltwitter.append(0)  
if len(total22)>=1:
  total22 = sum(total22)/len(total22);totaltwitter.append(total22) 
else:
  totaltwitter.append(0)  

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,totaletsy = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'ETSY':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'ETSY':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'ETSY':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'ETSY':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'ETSY':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'ETSY':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'ETSY':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'ETSY':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'ETSY':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'ETSY':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'ETSY':
    total22.append(a[2])

if len(total12)>=1:
  total12 = sum(total12)/len(total12);totaletsy.append(total12) 
else:
  totaletsy.append(0)  
if len(total13)>=1:
  total13 = sum(total13)/len(total13);totaletsy.append(total13)  
else:
  totaletsy.append(0)  
if len(total14)>=1:
  total14 = sum(total14)/len(total14);totaletsy.append(total14) 
else:
  totaletsy.append(0)  
if len(total15)>=1:
  total15 = sum(total15)/len(total15);totaletsy.append(total15) 
else:
  totaletsy.append(0)  
if len(total16)>=1:
  total16 = sum(total16)/len(total16);totaletsy.append(total16) 
else:
  totaletsy.append(0)  
if len(total17)>=1:
  total17 = sum(total17)/len(total17);totaletsy.append(total17) 
else:
  totaletsy.append(0)  
if len(total18)>=1:
  total18 = sum(total18)/len(total18);totaletsy.append(total18) 
else:
  totaletsy.append(0)  
if len(total19)>=1:
  total19 = sum(total19)/len(total19);totaletsy.append(total19) 
else:
  totaletsy.append(0)  
if len(total20)>=1:
  total20 = sum(total20)/len(total20);totaletsy.append(total20) 
else:
  totaletsy.append(0)  
if len(total21)>=1:
  total21 = sum(total21)/len(total21);totaletsy.append(total21) 
else:
  totaletsy.append(0)  
if len(total22)>=1:
  total22 = sum(total22)/len(total22);totaletsy.append(total22) 
else:
  totaletsy.append(0)  

totaletsy  

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,totalsnap = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'SNAP':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'SNAP':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'SNAP':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'SNAP':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'SNAP':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'SNAP':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'SNAP':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'SNAP':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'SNAP':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'SNAP':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'SNAP':
    total22.append(a[2])

if len(total12)>=1:
  total12 = sum(total12)/len(total12);totalsnap.append(total12) 
else:
  totalsnap.append(0)  
if len(total13)>=1:
  total13 = sum(total13)/len(total13);totalsnap.append(total13)  
else:
  totalsnap.append(0)  
if len(total14)>=1:
  total14 = sum(total14)/len(total14);totalsnap.append(total14) 
else:
  totalsnap.append(0)  
if len(total15)>=1:
  total15 = sum(total15)/len(total15);totalsnap.append(total15) 
else:
  totalsnap.append(0)  
if len(total16)>=1:
  total16 = sum(total16)/len(total16);totalsnap.append(total16) 
else:
  totalsnap.append(0)  
if len(total17)>=1:
  total17 = sum(total17)/len(total17);totalsnap.append(total17) 
else:
  totalsnap.append(0)  
if len(total18)>=1:
  total18 = sum(total18)/len(total18);totalsnap.append(total18) 
else:
  totalsnap.append(0)  
if len(total19)>=1:
  total19 = sum(total19)/len(total19);totalsnap.append(total19) 
else:
  totalsnap.append(0)  
if len(total20)>=1:
  total20 = sum(total20)/len(total20);totalsnap.append(total20) 
else:
  totalsnap.append(0)  
if len(total21)>=1:
  total21 = sum(total21)/len(total21);totalsnap.append(total21) 
else:
  totalsnap.append(0)  
if len(total22)>=1:
  total22 = sum(total22)/len(total22);totalsnap.append(total22) 
else:
  totalsnap.append(0)

total12,total13,total14,total15,total16,total17,total18,total19,total20,total21,total22,totalpinterest = ([] for i in range(12))

for i in range(len(Data)):
  a = list(df[i])
  b = list(Data[i])

  if b[2]=='1' and b[3]=='2' and a[1]== 'PINS':
    total12.append(a[2]) 

  if b[2]=='1' and b[3]=='3' and a[1]== 'PINS':
    total13.append(a[2])
  
  if b[2]=='1' and b[3]=='4' and a[1]== 'PINS':
    total14.append(a[2]) 
  
  if b[2]=='1' and b[3]=='5' and a[1]== 'PINS':
    total15.append(a[2])
  
  if b[2]=='1' and b[3]=='6' and a[1]== 'PINS':
    total16.append(a[2])
  
  if b[2]=='1' and b[3]=='7' and a[1]== 'PINS':
    total17.append(a[2])
  
  if b[2]=='1' and b[3]=='8' and a[1]== 'PINS':
    total18.append(a[2])
  
  if b[2]=='1' and b[3]=='9' and a[1]== 'PINS':
    total19.append(a[2])
  
  if b[2]=='2' and b[3]=='0' and a[1]== 'PINS':
    total20.append(a[2])
  
  if b[2]=='2' and b[3]=='1' and a[1]== 'PINS':
    total21.append(a[2])
  
  if b[2]=='2' and b[3]=='2' and a[1]== 'PINS':
    total22.append(a[2])

if len(total12)>=1:
  total12 = sum(total12)/len(total12);totalpinterest.append(total12) 
else:
  totalpinterest.append(0)  
if len(total13)>=1:
  total13 = sum(total13)/len(total13);totalpinterest.append(total13)  
else:
  totalpinterest.append(0)  
if len(total14)>=1:
  total14 = sum(total14)/len(total14);totalpinterest.append(total14) 
else:
  totalpinterest.append(0)  
if len(total15)>=1:
  total15 = sum(total15)/len(total15);totalpinterest.append(total15) 
else:
  totalpinterest.append(0)  
if len(total16)>=1:
  total16 = sum(total16)/len(total16);totalpinterest.append(total16) 
else:
  totalpinterest.append(0)  
if len(total17)>=1:
  total17 = sum(total17)/len(total17);totalpinterest.append(total17) 
else:
  totalpinterest.append(0)  
if len(total18)>=1:
  total18 = sum(total18)/len(total18);totalpinterest.append(total18) 
else:
  totalpinterest.append(0)  
if len(total19)>=1:
  total19 = sum(total19)/len(total19);totalpinterest.append(total19) 
else:
  totalpinterest.append(0)  
if len(total20)>=1:
  total20 = sum(total20)/len(total20);totalpinterest.append(total20) 
else:
  totalpinterest.append(0)  
if len(total21)>=1:
  total21 = sum(total21)/len(total21);totalpinterest.append(total21) 
else:
  totalpinterest.append(0)  
if len(total22)>=1:
  total22 = sum(total22)/len(total22);totalpinterest.append(total22) 
else:
  totalpinterest.append(0)  

total = [totalface,totaltwitter,totaletsy,totalsnap,totalpinterest]

#grafico das medias de abertura de cada ano

fig4 = px.bar(x = ['2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022'],y = total,title = 'Valor médio das aberturas das ações do facebook', )
fig4.update_yaxes (title = 'Valor de abertura')
fig4.update_xaxes(title = 'Anos')
fig4.show()

